// AUTH ACTIONS
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL";
export const GOOGLE_SIGN_OUT = "GOOGLE_SIGN_OUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FETCH_ERRORS = "FETCH_ERRORS";
// PROJECT ACTIONS
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS";
export const GET_ALL_PROJECTS_FAIL = "GET_ALL_PROJECTS_FAIL";
export const GET_ALL_USER_PROJECTS_SUCCESS = "GET_ALL_USER_PROJECTS_SUCCESS";
export const GET_ALL_USER_PROJECTS_FAIL = "GET_ALL_USER_PROJECTS_FAIL";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL";

export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
// FOR FUNDRAISERS / OWNERS OF PROJECTS (affects everyone related to the project)
export const CANCEL_PROJECT_SUCCESS = "CANCEL_PROJECT_SUCCESS";
export const CANCEL_PROJECT_FAIL = "CANCEL_PROJECT_FAIL";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_FAIL = "EDIT_PROJECT_FAIL";
export const EDIT_PROJECT_ICON_SUCCESS = "EDIT_PROJECT_ICON_SUCCESS";
export const EDIT_PROJECT_ICON_FAIL = "EDIT_PROJECT_ICON_FAIL";
export const UPDATE_PROJECT_NAME_SUCCESS = "UPDATE_PROJECT_NAME_SUCCESS";
export const UPDATE_PROJECT_NAME_FAIL = "UPDATE_PROJECT_NAME_FAIL";

// FOR DONORS TO PROJECTS
export const DONATE_TO_PROJECT_SUCCESS = "DONATE_TO_PROJECT_SUCCESS";
export const DONATE_TO_PROJECT_FAIL = "DONATE_TO_PROJECT_FAIL";
