export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL";
export const GOOGLE_SIGN_OUT = "GOOGLE_SIGN_OUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FETCH_ERRORS = "FETCH_ERRORS";
